version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DYNAMODB_ENDPOINT=db:8000
    command: ["sh", "-c", "npm install aws-sdk && npm install typescript && tsc /scripts/create-tables.ts && node /scripts/create-tables.js"]

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - '8000:8000'