version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DYNAMODB_ENDPOINT=db:8000

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - '8000:8000'